### ISSUE TITLE
🪲[Bug]: Enhancing the css of about us page.

### ISSUE THREAD

**Issue by vansh-sardana** [Abidsyed25/ScrapQuest#100]
**Describe the bug**
I want to contribute to this project by enhancing the css of the about us page quite similar to the login/signup page.

**Screenshots**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/107904311/40420ff3-ac18-46e5-9de3-45b353443b17)

**Comment by Abidsyed25** [comment]
@vansh-sardana go on

**Comment by komal-agarwal5** [comment]
@Abidsyed25 If the user is having problem in this issue I can take this up and complete it within 1 day
