### ISSUE TITLE
🪲[Bug]: Adding eye button on the login/signup page

### ISSUE THREAD

**Issue by vansh-sardana** [Abidsyed25/ScrapQuest#101]
**Describe the bug**
If one wants to see the password about what he typed, there should be a way to oversee the password.

**Expected behavior**
There should be an eye button there in order to toggle the password and verify it.
Will add on both login and signup pages.

**Screenshots**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/107904311/f6abdec1-838d-46c6-abec-3a3689960377)

![image](https://github.com/Abidsyed25/ScrapQuest/assets/107904311/d1e40ea3-8d4f-4c4b-999d-d15a2a4aff5d)

**Comment by Abidsyed25** [comment]
@vansh-sardana carry-on
