### ISSUE TITLE
💡[FEATURE]: Ask for the feedback type

### ISSUE THREAD

**Issue by AkhilaSunesh** [Abidsyed25/ScrapQuest#109]
**Is your feature request related to a problem? Please describe.**
In the feedback/contact section. It is not necessary to contact the only for an issue .

![image](https://github.com/Abidsyed25/ScrapQuest/assets/140897461/dde5a668-c2ef-4c5a-948a-30e5cbef812a)
![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/Abidsyed25/ScrapQuest/assets/140897461/11023a87-6da3-4a90-8760-c20e0f177969)

**Describe the solution you'd like**
a dropdown for easy segregation of messages

kindly assign me this issue

**Comment by Abidsyed25** [comment]
@AkhilaSunesh go on
