### ISSUE TITLE
🪲[Bug]:  Login button missing in Home page

### ISSUE THREAD

**Issue by Abidsyed25** [Abidsyed25/ScrapQuest#112]
**Describe the bug**
Login button missing in Home page. There is login page in /login url.

**Expected behavior**
Add a login button on the navbar of home page

**Comment by vansh-sardana** [comment]
I would like to take up this issue @Abidsyed25

**Comment by Abidsyed25** [comment]
@vansh-sardana go on

**Comment by thekumbhaj** [comment]
@vansh-sardana  what is the status?

**Comment by vansh-sardana** [comment]
Hey @thekumbhaj, its already present there (begin your journey)
