### ISSUE TITLE
🪲[Bug]: Error in autocomment in Pull_Request_template.tmd

### ISSUE THREAD

**Issue by vansh-sardana** [Abidsyed25/ScrapQuest#116]
**Describe the bug**
As we create a pull request, we get an error stating auto comment failed as in the ss below.

**To Reproduce**
create a pull request and see notifications in github

**Expected behavior**
We should get a comment saying thank you instead of the error.

**Screenshots**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/107904311/ceff2400-eb43-4d9e-a309-8228fa31a22a)

**Additional context**
I have corrected this error. Kindly assign me this issue as a contributor under GSSOC'24.
![image](https://github.com/Abidsyed25/ScrapQuest/assets/107904311/d6f18ee2-64d1-4c4f-8c05-75d3d3ed3079)

**Comment by Abidsyed25** [comment]
@vansh-sardana still error persists

**Comment by vansh-sardana** [comment]
let me check once sir

**Comment by vansh-sardana** [comment]
It did work on my branch. see this pull request https://github.com/vansh-sardana/ScrapQuest/pull/1#issuecomment-2182181706. Will work on it to see where else may be the issue.
