### ISSUE TITLE
💡[FEATURE]: Contact us Styling 

### ISSUE THREAD

**Issue by Damini2004** [Abidsyed25/ScrapQuest#124]
**Is your feature request related to a problem? Please describe.**
Not attractive
**Describe the solution you'd like**
Help to grab more user attention
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/119414762/75d2f305-1c64-4831-b6ea-396b12480f7f)

**Comment by Abidsyed25** [comment]
@Damini2004  ok

**Comment by komal-agarwal5** [comment]
@Abidsyed25 I can complete this work within 1 day ,if the above user is facing difficulty can u please assign this issue to me?

**Comment by Abidsyed25** [comment]
@komal-agarwal5 If you want to work upon it then open a new issue.
