### ISSUE TITLE
🪲[Bug]: Hamburger icon needs to be replace with close icon if menu open up

### ISSUE THREAD

**Issue by kapilG0** [Abidsyed25/ScrapQuest#127]
**Describe the bug**
Hamburger icon needs to be replace with close icon if menu opens up

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/59639410/5403fc51-6183-4302-ba93-1f2ca2955b0e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @Abidsyed25 please assign this issue to me under gssoc 24

**Comment by Abidsyed25** [comment]
@kapilG0 ok
