### ISSUE TITLE
Home_Page UI

### ISSUE THREAD

**Issue by Rohitha-pudu** [Abidsyed25/ScrapQuest#13]
### Home_page UI
Need improvements on the UI 
-A Proper Landing Page
-Footer
-I will work on this issue .Please assign this to me under GSSOC24.
-Please mention the level

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.
