### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [Abidsyed25/ScrapQuest#130]
Hello Project Admin
I would like to add Icons to Navbar to make website attractive
Can you assign me this issue under GSSOC'24 @Abidsyed25 

![IMG_20240627_204621](https://github.com/Abidsyed25/ScrapQuest/assets/161804629/16f58344-758e-4020-8f85-be1230a8c4af)

**Comment by Abidsyed25** [comment]
@sailaja-adapa ok

**Comment by sailaja-adapa** [comment]
@Abidsyed25 Can you add label level 1 or level 2 Under GSSOC'24
