### ISSUE TITLE
💡[FEATURE]: Add a Terms and Conditions Page

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Abidsyed25/ScrapQuest#132]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem. It is related to an additional feature request.

**Describe the solution you'd like**
I would like to add a Terms and Conditions Page and provide its quicklink in the footer section.  

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by Abidsyed25** [comment]
@ParnaRoyChowdhury777 ok
