### ISSUE TITLE
💡[FEATURE]: Redesign the UI of FAQ page

### ISSUE THREAD

**Issue by komal-agarwal5** [Abidsyed25/ScrapQuest#135]
**Is your feature request related to a problem? Please describe.**
I wish to Redesign the UI of FAQ page

**Describe the solution you'd like**
I want to make use of accordions flexed one after another to give a good view

**Describe alternatives you've considered**

**Additional context**

**Comment by Abidsyed25** [comment]
@komal-agarwal5 ok
