### ISSUE TITLE
💡[FEATURE]: Add Hover Effect to Social Media Icons in Footer

### ISSUE THREAD

**Issue by AsmitaMishra24** [Abidsyed25/ScrapQuest#139]
**Is your feature request related to a problem? Please describe.**
Currently, the social media icons in the footer are static and do not provide any visual feedback when a user hovers over them. Adding a hover effect will enhance the user experience by making the icons more interactive and visually appealing.

**Describe the solution you'd like**
1. Hover Effect: Implement a visual change when the user hovers over each social media icon.
2. Color Change: The icon color should change to a predetermined color (e.g., a slightly lighter or darker shade, or a completely different color that matches the brand guidelines).
3. Transition: The color change should have a smooth transition effect (e.g., 0.3 seconds ease-in-out) to make it visually pleasing.

**Comment by Abidsyed25** [comment]
@AsmitaMishra24 ok
