### ISSUE TITLE
💡[FEATURE]: Add Privacy Policy Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [Abidsyed25/ScrapQuest#140]
**Is your feature request related to a problem? Please describe.**
To ensure that users are aware of how their personal information is handled, we need to add a dedicated Privacy Policy page. This page will provide clear and comprehensive information about our data collection practices, user rights, and privacy practices.

**Describe the solution you'd like**
Content:
- Draft or obtain the legal text for the Privacy Policy page. This content should be reviewed and approved by the legal team.
- The content should cover areas such as:
- Data collection practices
- Use of collected data
- Data sharing and third-party disclosures
- User rights regarding their data
- Cookie usage
- Security measures
- Any other relevant privacy information

 Design:
- The page should follow the existing design guidelines and aesthetic of the website.
- Include headings and subheadings for easy navigation of the content.
- Ensure the text is readable with appropriate font size and color contrast.

Navigation:
- Add a link to the Privacy Policy page in the footer of the website.
- Ensure the link is visible and accessible on all pages of the site.

SEO:
- Optimize the page for search engines by including relevant keywords and meta descriptions.
- Add appropriate title and meta tags.

**Describe alternatives you've considered**
NA

**Comment by Abidsyed25** [comment]
@AsmitaMishra24 ok
