### ISSUE TITLE
🪲[Bug]: Footer is faulty

### ISSUE THREAD

**Issue by AMS003010** [Abidsyed25/ScrapQuest#143]
**Describe the bug**
The footer position seems to be fixed to the bottom of the viewport screen and hence it is seen always and it is overlapping over content hindering visibility.

**To Reproduce**
1. Go to the [website](https://scrap-quest.vercel.app/)
2. Observe the bottom of the screen
3. See error

**Expected behavior**
The footer is supposed to be present at the bottom of all content and not at the bottom of the viewport screen. 

**Screenshots**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/111883236/706ffd99-8585-4168-9571-eeafa3514993)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 22

**Additional context**
Please do assign me this issue as I would like to work on this under gssoc'24.

**Comment by Abidsyed25** [comment]
@AMS003010 Ok

**Comment by AMS003010** [comment]
@Abidsyed25 
I have made a PR
Please do review it.
