### ISSUE TITLE
💡[FEATURE]: Adding a Careers Page

### ISSUE THREAD

**Issue by Ojas-Arora** [Abidsyed25/ScrapQuest#144]
**Is your feature request related to a problem? Please describe.**
@Abidsyed25 I want to add a careers page to the website. Kindly assign this issue to me.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Ojas-Arora** [comment]
@Abidsyed25 Can i also work on this issue?

**Comment by Ojas-Arora** [comment]
@Abidsyed25 Kindly please tell whether u require this issue or not?

**Comment by Abidsyed25** [comment]
@Ojas-Arora careers page not required

**Comment by Ojas-Arora** [comment]
@Abidsyed25 ok
