### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by Abidsyed25** [Abidsyed25/ScrapQuest#15]
In the readme file, contribution guidelines link is not working. When clicked on contribution guidelines it should navigate to the code of conduct file.
Also make changes in the first two steps to set project locally.
1. git clone https://github.com/Abidsyed25/scrapquest.git
2. cd scrapquest

**Comment by SuperSahitya** [comment]
Hello @Abidsyed25. I would like to fix the issues with the README.md file. Please assign the issue to me.

**Comment by Varun-Sethi-Dev** [comment]
Assign this issue to me i will fix it

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by Ayushigitgithub** [comment]
hii @Abidsyed25 
i would like to work on this project s could you please assign this issue to me

**Comment by Abidsyed25** [comment]
@SuperSahitya go for it.
