### ISSUE TITLE
🪲[Bug]: navbar options to seem to disappear on hovering 

### ISSUE THREAD

**Issue by Prabhatyadav60** [Abidsyed25/ScrapQuest#152]
**Describe the bug**
When hovering over the navbar section, the poor color selection causes the navbar options to seem to disappear.

**To Reproduce**
Go to the ScrapQuest homepage.
Hover over any option in the navbar (Home, About Us, Contact, etc.).
Observe the color change.
**Expected Behavior**
The navbar options should remain visible and legible when hovered over.

**Screenshots**

https://github.com/Abidsyed25/ScrapQuest/assets/133522303/2358f848-faf3-451e-8662-785a58eb36c0

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Device: [Poco M2 Pro]
 - OS: [Android]
 - Browser [Chrome]

**Additional context**

**Comment by Abidsyed25** [comment]
@Prabhatyadav60 ok
