### ISSUE TITLE
Enhancing Readme.md

### ISSUE THREAD

**Issue by Aditijainnn** [Abidsyed25/ScrapQuest#153]
Readme.md looks fine but by adding some markdown features , icons and adding Gssoc image it will look more cool.
Please assign this to me under Gssoc'24

**Comment by Abidsyed25** [comment]
@Aditijainnn ok

**Comment by Abidsyed25** [comment]
@Aditijainnn please enhance readme as soon as possible

**Comment by Aditijainnn** [comment]
> @Aditijainnn please enhance readme as soon as possible

OK

**Comment by Aditijainnn** [comment]
> @Aditijainnn please enhance readme as soon as possible

its done
