### ISSUE TITLE
Issue template is not working

### ISSUE THREAD

**Issue by Abidsyed25** [Abidsyed25/ScrapQuest#16]
Issue template for this project is not working as expected. Check the code and correct it.

**Comment by officeneerajsaini** [comment]
@Abidsyed25 i will fix .

**Comment by officeneerajsaini** [comment]
@Abidsyed25  check my pr

**Comment by Shirapti-nath** [comment]
Id like to work on this project can you accept me sir

**Comment by officeneerajsaini** [comment]
@Shirapti-nath  are you talking about project or issue !

**Comment by Shirapti-nath** [comment]
Project

**Comment by officeneerajsaini** [comment]
@Shirapti-nath  why not , you can contribute on any issue ..
