### ISSUE TITLE
💡[FEATURE]: Add a preloader in website

### ISSUE THREAD

**Issue by komal-agarwal5** [Abidsyed25/ScrapQuest#179]
**Is your feature request related to a problem? Please describe.**
I want to add a preloader to give an enhanced look when loading the home page

**Describe the solution you'd like**
I would like to add this
**Describe alternatives you've considered**

**Additional context**

**Comment by Abidsyed25** [comment]
@komal-agarwal5  where do you want to add the preloader?

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 where do you want to add the preloader?

@Abidsyed25 
I was thinking to add when home page is loaded
Any other suggestion if you have you can give,will do like that only then

**Comment by Abidsyed25** [comment]
@komal-agarwal5 but there is no delay in loading of the home page. I think its not necessary.

**Comment by komal-agarwal5** [comment]
@Abidsyed25 Ok do let me know if you want it for any other page ,I will be happy to do it
