### ISSUE TITLE
🪲[Bug]: The language translator is not visible properly

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Abidsyed25/ScrapQuest#183]
**Describe the bug**
The language translator button is not properly visible.

**To Reproduce**

**Expected behavior**
It should be visible properly at the top right end

**Screenshots**
![Screenshot 2024-07-21 060848](https://github.com/user-attachments/assets/bc8f2494-bd91-4f0f-a74e-cd9b2b45ef2a)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser: Microsoft Edge
 - Version

**Comment by Abidsyed25** [comment]
@ParnaRoyChowdhury777 ok
