### ISSUE TITLE
🌟Enhancement: Improving the "FAQ Section" of the Website!

### ISSUE THREAD

**Issue by aslams2020** [Abidsyed25/ScrapQuest#187]
Hey @Abidsyed25 ,

I would like to enhance the UI and functionality of the current FAQ page to improve user experience.

### Here's what I Will do:
- **Styling it to follow the Website's theme.**
- Add **collapsible sections for questions** to streamline navigation and reduce clutter.
- **Update existing content and add new comprehensive questions** based on user feedback and common inquiries.
- **Adding transition moving effect to the FAQ sections questions.**

For example like this - ( I will follow the theme of the ScrapQuest Website) 
![image](https://github.com/user-attachments/assets/06ce08a3-c894-4fc6-b41e-f1b6668fbcb8)

Please assign me under GSSOC'24.
Looking forward to contributing to our project!
thankyou!

### Use Case

The more Comprehensive questions and the more better functionality an FAQ Section have....The more it will enhance the smooth and better user experience.

**Comment by Abidsyed25** [comment]
@aslams2020 ok
