### ISSUE TITLE
FEATURE 🌟: Improve The Styling of About Us Page

### ISSUE THREAD

**Issue by Tejashri-Taral** [Abidsyed25/ScrapQuest#188]
Hey @Abidsyed25 ,

**Here is the feature I want to request -**
Currently the About Us Section is a little bit Unreadable and is not following the website's theme.
Also, It is divided into subsections which is not readable.

**Here :**
![image](https://github.com/user-attachments/assets/9e2b33e5-3731-458f-98e9-cdfa2f84a633)

******Here's What Will I Do -******
I Want to make it Readable with Brief and Clear Information regarding the Website .
I Also Like to change the Alignment/UI of the Section, As a Introductory page should be readable and understandable for the Visitors to know more about the Website.
I would also like to Style the Section to follow the website's Color theme.
Adding Animations, hovering effects wherever necessary
And also, changing the background of the page with an image related to the website

**Are you contributing under any open-source program?**
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by Abidsyed25** [comment]
@Tejashri-Taral ok
