### ISSUE TITLE
Adding Footer Description to ScrapQuest! ✨

### ISSUE THREAD

**Issue by aslams2020** [Abidsyed25/ScrapQuest#198]
Hey @Abidsyed25 

In the website's footer section, there is a noticeable empty space below the website logo. This space should be utilized by adding a brief description of the website to provide users with more context and enhance the footer's informational value.

**like this -** 
![image](https://github.com/user-attachments/assets/dc0364b5-0acb-4aff-b31a-0975191b924a)

**Current Footer- **
![image](https://github.com/user-attachments/assets/08f9c2f7-d34d-41eb-a1ad-0927a78584bd)

### Expected Behavior
The empty space below the website logo in the footer should contain a brief description of the website. This description can include information about the website's purpose, mission, or any other relevant details that provide users with a better understanding of the site.

**Comment by Abidsyed25** [comment]
@aslams2020 description not needed. It looks fine now

**Comment by aslams2020** [comment]
ohk @Abidsyed25 , I Understand!
