### ISSUE TITLE
Login feature

### ISSUE THREAD

**Issue by Chelseasingla1** [Abidsyed25/ScrapQuest#20]
I would like to add a feature where user login first then able to access website.
Please assign me this issue under GSSoC'24.

**Comment by Abidsyed25** [comment]
I think login is not necessary atleast upto now. Maybe we can consider it in future.

**Comment by Chelseasingla1** [comment]
> I think login is not necessary atleast upto now. Maybe we can consider it in future.

@Abidsyed25 Then can you please assign me a issue where i can work on?

**Comment by Abidsyed25** [comment]
Yeah sure, If I found any issue I will assign it to you. Till then if you find any bug in the existing site you can open an issue and work on it.

**Comment by Chelseasingla1** [comment]
> Yeah sure, If I found any issue I will assign it to you. Till then if you find any bug in the existing site you can open an issue and work on it.

Okay thankyou!!
