### ISSUE TITLE
➕Feature : Styling The "Vertical Scroll Bar"  To Match WebsiteTheme!

### ISSUE THREAD

**Issue by aslams2020** [Abidsyed25/ScrapQuest#205]
Hey @Abidsyed25 

I Want to **make an Enhancement for the Vertical Scroll bar** in the Right Side.
Currently it is not styled (it's default) to follow the Website's theme.

### **As you can see-** 

![image](https://github.com/user-attachments/assets/c2a82833-acea-4b8a-901f-50f8cab28592)

### **This is How I Want to Enhance it to follow the Website theme**

![image](https://github.com/user-attachments/assets/39f00bea-98ef-420e-bff8-12728460702a)

Please take a look. 
I would like to work on it, Please assign me.

Thankyou!

**Comment by Abidsyed25** [comment]
@aslams2020 ok
