### ISSUE TITLE
Improving the UI of the landing page

### ISSUE THREAD

**Issue by PrathicaShettyM** [Abidsyed25/ScrapQuest#21]
@Abidsyed25 I would like to improve the UI of the landing page. Please assign me this task under GSSoC'24.

**Comment by Abidsyed25** [comment]
@PrathicaShettyM I need more clarity on it. What exactly do you want to change. Any examples?

**Comment by PrathicaShettyM** [comment]
Sir I would like to improve the font-styles, hovering effects for website so it looks more appealing for the users

**Comment by TheAshutoshGupta** [comment]
@Abidsyed25 i want to make hero section interactive and also make it visually appealing. Assign it to me. i can give references of how i will be doing it.

- Text in the hero section needs to be optimized for the background
- Search bar is touching the edges if we check the responsiveness, need to make it responsive.
- certain graphics can be added in hero section, it will be hit and trial for which is looking good.

**Comment by Abidsyed25** [comment]
@TheAshutoshGupta Hey, you can open a new issue. I will assign it to you.

**Comment by Abidsyed25** [comment]
@PrathicaShettyM go for it

**Comment by PrathicaShettyM** [comment]
Yes sir

**Comment by PrathicaShettyM** [comment]
Sir I'm having an issue in clonning this website.
``` cd quine-scrapquest``` is this the correct folder to navigate after cloning the project sir?
But its showing such a folder doesnt exist

**Comment by Abidsyed25** [comment]
@PrathicaShettyM 
use below commands:
step 1: git clone https://github.com/Abidsyed25/ScrapQuest.git
step 2: cd scrapquest
step 3: npm install
step 4 : npm run dev

**Comment by thekumbhaj** [comment]
@PrathicaShettyM  are you working in the issue?

**Comment by PrathicaShettyM** [comment]
Yes
