### ISSUE TITLE
💡[FEATURE]: Improving home page

### ISSUE THREAD

**Issue by YadlaMani** [Abidsyed25/ScrapQuest#25]
**Is your feature request related to a problem? Please describe.**
I would like to imporove the home page 

**Describe the solution you'd like**
Firstly i would change the text color because it's apperance is really low and try to add some space theme background or some good background to match the vibe plain black background doesn't suit well
# Screenshot
![image](https://github.com/Abidsyed25/ScrapQuest/assets/133841094/c8f71a96-c56f-42bf-87e2-e5bf80deec02)

**Comment by YadlaMani** [comment]
@Abidsyed25 pls assign me this issue under gssoc'24

**Comment by Mastermind730** [comment]
@Abidsyed25  please assign me this issue.I have good experience on working on Next js and tailwind and have also won a hackathon

**Comment by Abidsyed25** [comment]
@YadlaMani go for it
