### ISSUE TITLE
💡[FEATURE]: Add a favicon to the website

### ISSUE THREAD

**Issue by SnehansuBehera** [Abidsyed25/ScrapQuest#26]
**Is your feature request related to a problem? Please describe.**
The website doesn't have a favicon. It needs a favicon for symbolic representation of the website

**Describe the solution you'd like**
I would like to add a favicon to the website which will represent the view of the website.

**Additional context**
![Screenshot 2024-05-16 210432](https://github.com/Abidsyed25/ScrapQuest/assets/121883802/a8eea9bc-8c40-447a-9760-488863b07955)

**Comment by SnehansuBehera** [comment]
hey @Abidsyed25 i would like to contribute the issue under gssoc'24.

**Comment by Abidsyed25** [comment]
@SnehansuBehera  Add any related icon

**Comment by SnehansuBehera** [comment]
Yup @Abidsyed25 I am up for it.
