### ISSUE TITLE
Add aurora background 

### ISSUE THREAD

**Issue by anshulsoni4** [Abidsyed25/ScrapQuest#27]
**Is your feature request related to a problem? Please describe.**
Aurora bg using aceternity

**Describe the solution you'd like**
![image](https://github.com/Abidsyed25/ScrapQuest/assets/74638335/3d2179b5-45d1-4fd8-8655-45f5d5ee5c32)

**Describe alternatives you've considered**

**Additional context**

**Comment by Abidsyed25** [comment]
@anshulsoni4 go for it

**Comment by Abidsyed25** [comment]
@anshulsoni4 any update?
