### ISSUE TITLE
Add loader to webpage

### ISSUE THREAD

**Issue by anshulsoni4** [Abidsyed25/ScrapQuest#28]
**Is your feature request related to a problem? Please describe.**
Adding a loading animation after we click 

**Describe the solution you'd like**
there is no loading animation or component for this, will be adding that

**Describe alternatives you've considered**

**Additional context**

**Comment by Abidsyed25** [comment]
@anshulsoni4 go for it

**Comment by Abidsyed25** [comment]
@anshulsoni4 any update?
