### ISSUE TITLE
📝[Docs]: Pull Request Template Creation

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Abidsyed25/ScrapQuest#30]
**What Docs changes are you proposing?**
Provide a clear description of the changes you're proposing for the documentation. Are you suggesting corrections, clarifications, additions, or updates?
I am writing to express my interest in contributing to your repository by creating a pull request template. 
I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests. 
Could you please assign me the issue under gssoc24? I am excited about the opportunity to contribute to your project and help improve the workflow for all contributors.

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
Explain the motivation behind the proposed changes and how they will benefit the community or users of the documentation.

**Describe the solution you'd like**
Provide a clear and concise description of the changes you'd like to see implemented in the documentation.

**Describe alternatives you've considered**
If you've thought about alternative approaches or solutions, briefly describe them here.

**Additional context**
Add any additional context, examples, or screenshots related to the proposed documentation changes.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Could you please assign it to me.

**Comment by kartikayasijaa** [comment]
@PradnyaGaitonde What's the update on this issue?

**Comment by PradnyaGaitonde** [comment]
Will get it done in a few hours.
