### ISSUE TITLE
💡[FEATURE]:  Add an Contact Page

### ISSUE THREAD

**Issue by Manav173** [Abidsyed25/ScrapQuest#32]
Add a Contact Page

Is your feature request related to a problem? Please describe.
Users often struggle to find ways to get in touch with our team. Without a dedicated contact page, it becomes challenging for users to reach out for support, provide feedback, or make inquiries, leading to a poor user experience and potential loss of engagement.

Describe the solution you'd like
I would like to have a dedicated Contact Page on our website that provides users with various methods to reach us. 

I would be really thankful if you assign me this issue as a part of GSSoC'24 @Abidsyed25 .

**Comment by Abidsyed25** [comment]
@Manav173 go for it

**Comment by Abidsyed25** [comment]
@Manav173 any update?

**Comment by Manav173** [comment]
Will raise a PR by Thursday just completing the work.
