### ISSUE TITLE
💡[FEATURE]: Add an About Us Page

### ISSUE THREAD

**Issue by roysammy** [Abidsyed25/ScrapQuest#33]
**Is your feature request related to a problem? Please describe.**
Users often express frustration when they cannot easily find information about our company, our mission, and the team behind our products. This lack of transparency can lead to mistrust or a sense of detachment from our brand. An About Page is crucial for providing this information in a clear and accessible manner.

**Describe the solution you'd like**
We propose the addition of an About Page to our website.

### Please assign me this issue as part of GSSoC'24 @Abidsyed25 . Thank you!

**Comment by Abidsyed25** [comment]
@roysammy123 go for it

**Comment by roysammy** [comment]
@Abidsyed25 thanks for assigning this. Can you please add label of level 1/2/3 for this issue?
