### ISSUE TITLE
💡[FEATURE]: implement the scrape the website images

### ISSUE THREAD

**Issue by CoderSwarup** [Abidsyed25/ScrapQuest#38]
**Is your feature request related to a problem? Please describe.**

their is an the feature that are enable user to fetch the images from the website that they required

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

please assign me this issue

**Comment by CoderSwarup** [comment]
@kartikayasijaa please add the GSSoC'24 label and level

**Comment by Abidsyed25** [comment]
@CoderSwarup any update?
