### ISSUE TITLE
💡[FEATURE]: Add a Pull Request Template

### ISSUE THREAD

**Issue by Asymtode712** [Abidsyed25/ScrapQuest#40]
### Describe the feature

Often, pull requests lack necessary details, making it difficult for reviewers to understand the changes, the reasons behind them, and how to test them. This can lead to delays in the review process, increased back-and-forth communication, and potential oversight of critical issues.
The solution is to implement a standardized pull request template. This template should include sections that prompt the author to provide essential information, such as:

- A brief description of the changes.
- The issue or feature being addressed (linked to relevant issue tracker entries).
- Screenshots or GIFs (if the changes include UI modifications).
- Checklist for confirming code adheres to coding standards, tests are added/updated, and documentation is updated.

### Add ScreenShots

![Pull Req](https://github.com/Abidsyed25/ScrapQuest/assets/115717746/39944089-3fc3-4d47-b99e-8771c5e98057)

**Comment by Asymtode712** [comment]
@kartikayasijaa please assign me this issue under gssoc'24

**Comment by Abidsyed25** [comment]
@Asymtode712 go for it
