### ISSUE TITLE
💡[FEATURE]: Dark Theme

### ISSUE THREAD

**Issue by Asymtode712** [Abidsyed25/ScrapQuest#48]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using the web app for extended periods, especially in low-light environments or at night. The bright, white background causes eye strain and discomfort, making it difficult to focus and increasing fatigue. Additionally, the lack of a dark theme makes the app less visually appealing and less in line with modern user interface trends, which many users prefer for its aesthetic and ergonomic benefits.

**Describe the solution you'd like**
I would like the web app to offer a dark theme option. This theme should replace the bright, white backgrounds with darker shades (e.g., dark grey or black) and adjust text and other UI elements to ensure readability against the dark background. Ideally, the dark theme should be easily switchable from the settings menu or even automatically triggered based on system-wide settings (e.g., following the device’s dark mode settings). This will help reduce eye strain, enhance focus, and improve the overall user experience, especially in low-light conditions.

@Abidsyed25 please assign me this issue

**Comment by Abidsyed25** [comment]
@Asymtode712 website is dark by default now. Try to add white or light color theme.

**Comment by Abidsyed25** [comment]
@Asymtode712 any update?

**Comment by Asymtode712** [comment]
@Abidsyed25 Sorry for the delay was busy in intern work, will raise a PR soon
