### ISSUE TITLE
Text animtion for better UX

### ISSUE THREAD

**Issue by Rohitha-pudu** [Abidsyed25/ScrapQuest#49]

**Comment by Abidsyed25** [comment]
@Rohitha-pudu Where do want to add text animation and what animation it will be?

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/Abidsyed25/ScrapQuest/assets/116823590/a40baaf2-1f74-4dff-8a07-a18cb0c75def)
Typewriter animation /text reveal animation and moving border animation to button

**Comment by Abidsyed25** [comment]
@Rohitha-pudu go for it.
