### ISSUE TITLE
Missing Learn.md File

### ISSUE THREAD

**Issue by Varun-Sethi-Dev** [Abidsyed25/ScrapQuest#5]
ScrapQuest should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons.

**Comment by Varun-Sethi-Dev** [comment]
Assign this task to me.

**Comment by Abidsyed25** [comment]
@Varun-Sethi-Dev go for it

**Comment by officeneerajsaini** [comment]
@Varun-Sethi-Dev can you tell me about what is learn.md file .

**Comment by Abidsyed25** [comment]
#19
