### ISSUE TITLE
💡[FEATURE]: Add Navigation Menu in the top of the website

### ISSUE THREAD

**Issue by roysammy** [Abidsyed25/ScrapQuest#50]
**Is your feature request related to a problem? Please describe.**
Currently there is no navigation menu present in the website, which is an essential thing needed in any website to navigate between webpages.

**Describe the solution you'd like**
I would implement a clean, visually attractive navigation menu by making use of ShadCN UI components.

#### @Abidsyed25 please assign me this issue as part of GSSOC'24. Thank you!

**Comment by Abidsyed25** [comment]
@roysammy123 go for it.

**Comment by Abidsyed25** [comment]
@roysammy123 any update?

**Comment by roysammy** [comment]
@Abidsyed25 It's done, just waiting for you to merge the PR for contact page so that I can raise the PR for this one
