### ISSUE TITLE
💡[FEATURE]:  Footer for the website

### ISSUE THREAD

**Issue by Abidsyed25** [Abidsyed25/ScrapQuest#59]
**Is your feature request related to a problem? Please describe.**
This website needs a footer with a copyright icon and year.

**Comment by gdhyani** [comment]
I can work on it.

**Comment by Abidsyed25** [comment]
@gdhyani ok

**Comment by gdhyani** [comment]
@Abidsyed25 Done !
#61

**Comment by gdhyani** [comment]
@thekumbhaj, please, here's my PR #61. Would you kindly check it as well?
