### ISSUE TITLE
💡[FEATURE]: Create custom 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Abidsyed25/ScrapQuest#63]
**Is your feature request related to a problem? Please describe.**
Create a custom 404 not found page for your website

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
now the error page looks like 
![image](https://github.com/Abidsyed25/ScrapQuest/assets/125277258/d27db429-b12e-4494-8fee-9a053cde477e)

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Abidsyed25/ScrapQuest/assets/125277258/382cddea-5b11-4468-8986-a28d6ff234f1)
you can select among the pics i can implement that

**Comment by RamakrushnaBiswal** [comment]
@Abidsyed25 can i work upon the issue

**Comment by Abidsyed25** [comment]
@RamakrushnaBiswal first pic looks good

**Comment by VaibhavYT** [comment]
it's already two days if you can assign me this I can complete it by today

**Comment by RamakrushnaBiswal** [comment]
I am working upon it @VaibhavYT
