### ISSUE TITLE
💡[FEATURE]:  Create the logo fro ScrapQuest

### ISSUE THREAD

**Issue by namandude** [Abidsyed25/ScrapQuest#70]
I want to create the logo for Scrap Quest .
Please assign this me under gssoc i would like to work on this.

**Comment by namandude** [comment]
![Screenshot 2024-06-12 143822](https://github.com/Abidsyed25/ScrapQuest/assets/118013565/e4149aef-0a5b-4d6e-b83d-f05bebc3a07c)

**Comment by Abidsyed25** [comment]
@namandude Hey, I thought you would add it onto the website. If not then I will close this issue.

**Comment by namandude** [comment]
This is what i m adding 
that just i shared so u letting know this.

**Comment by Abidsyed25** [comment]
@namandude I am closing this issue. You can raise a PR for footer issue.
