### ISSUE TITLE
💡[FEATURE]: Add  About us Page

### ISSUE THREAD

**Issue by namandude** [Abidsyed25/ScrapQuest#72]
I would like to add the about us page so that user can know what actually we do .
![Screenshot 2024-06-09 121047](https://github.com/Abidsyed25/ScrapQuest/assets/118013565/50f1f009-7f1f-437c-8562-2bb35fd22f94)
There in the navbar i will be adding the about us page where user can know how and why we were helping them.
Please assign  this me under gssoc  , i would like to work on this.
Thank You

**Comment by Abidsyed25** [comment]
@namandude go for it
