### ISSUE TITLE
💡[FEATURE]: Add Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [Abidsyed25/ScrapQuest#75]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
I would like to add a Login/Sign Up Page in the navbar on the top. Kindly assign this issue to me @Abidsyed25  

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Abidsyed25** [comment]
@Ojas-Arora ok
