### ISSUE TITLE
💡[FEATURE]: Modify Navbar 

### ISSUE THREAD

**Issue by Abidsyed25** [Abidsyed25/ScrapQuest#83]
**Is your feature request related to a problem? Please describe.**
Navbar is not looking good on the website.  Remodeling navbar is required. 

**Describe the solution you'd like**
The buttons should be changed into links. For reference, Navbar like in below picture will be suitable for the website. 

![My-Logo](https://github.com/Abidsyed25/ScrapQuest/assets/116893970/34498d8f-4754-4841-b47d-bafd425515ab)

**Comment by Ojas-Arora** [comment]
@Abidsyed25 I can make the navbar look like the same in the above code and have even made the same in my local . Kindly assign this issue to me.

**Comment by Abidsyed25** [comment]
@Ojas-Arora ok
