### ISSUE TITLE
💡[FEATURE]: Build a Testimonials Page with sliding carousel

### ISSUE THREAD

**Issue by komal-agarwal5** [Abidsyed25/ScrapQuest#84]
**Is your feature request related to a problem? Please describe.**
I wish to add a Testimonials Page with sliding carousel wherein the review of the users can be displayed.

**Describe the solution you'd like**
This will attract more users to the website.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Abidsyed25** [comment]
@komal-agarwal5 hey, could you add carousal in the home page with another section. It would look good on the website.

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 hey, could you add carousal in the home page with another section. It would look good on the website.

Yeah sure 
You mean like the testimonials thing will not be a separate page and be added in the home page only below right?

**Comment by komal-agarwal5** [comment]
@Abidsyed25 In case you liked the work is it please possible to increase the level as it required infinite moving cards component as well as then mapping it in final page?

**Comment by komal-agarwal5** [comment]
@Abidsyed25  In case you liked the work is it please possible to increase the level as it required infinite moving cards component as well as then mapping it in final page? PR #129
