### ISSUE TITLE
💡[FEATURE]: Adding signin functionality

### ISSUE THREAD

**Issue by kashnx** [Abidsyed25/ScrapQuest#88]
Code the logic for signin page so that user can login into his account

**Comment by Abidsyed25** [comment]
@kashnx How will you add database?

**Comment by kashnx** [comment]
Will connect it to mongodb .

**Comment by Abidsyed25** [comment]
@kashnx while creating PR add env variable instead of actual url.

**Comment by kashnx** [comment]
Kindly assign level labell to it
