### ISSUE TITLE
The download button should work on pressing the enter after pasting the link and not manually hover and click on downlaod button

### ISSUE THREAD

**Issue by Utsavladia** [Abidsyed25/ScrapQuest#97]
**Is your feature request related to a problem? Please describe.**
The download button should work on pressing the enter of keyboard to enhance the user experience

**Describe the solution you'd like**
I willl add the form like feature to press enter and start download instead of manually going with curser to the download button of website

![image](https://github.com/Abidsyed25/ScrapQuest/assets/124615886/28f9c4d7-6b9f-44fa-9e2d-f890f2789280)

i would love to contribute to this project and make it better for the users.
Please assign this to me under GSSOC 😊

**Comment by Abidsyed25** [comment]
@Utsavladia go on
